Update lemmy.yml
LemmyNet/lemmy-ansible pull request #36
Opened 2022-04-10 00:24 UTC by DMTryptamines

https://github.com/LemmyNet/lemmy-ansible/issues/35

2022-04-11 12:10 UTC, Nutomic commented
This doesnt look correct. I think the problem is that `isreg` is only set if the file exists. So the correct condition is probably `reg_enabled.stat.exists and reg_enabled.stat.isreg`.

cc @fadelkon

2022-04-11 12:57 UTC, fadelkon commented
El 11 d’abril de 2022 14:10:40 CEST, Nutomic ***@***.***> ha escrit:
>This doesnt look correct. I think the problem is that `isreg` is only set if the file exists.

I see

>  So the correct condition is probably `reg_enabled.stat.exists and reg_enabled.stat.isreg`.
>
>cc @fadelkon 
>

Sure, makes sense!

2022-04-11 18:52 UTC, dessalines requested changes

2022-04-11 18:52 UTC, dessalines commented on lemmy.yml
> -        when: reg_enabled.stat.isreg
reg_enabled.stat.exists and reg_enabled.stat.isreg

2022-04-12 20:24 UTC, DMTryptamines reviewed
Tested and can confirm r`eg_enabled.stat.exists and reg_enabled.stat.isreg` completed a fresh install fine where 'reg_enabled.stat.isreg` alone did not.

2022-04-12 21:25 UTC, merged

2022-04-12 21:25 UTC, dessalines commented
Thanks!